version: '3'

networks:
    app-network:
        driver: bridge

services:
    cache:
        image: redis:6.2-alpine
        container_name: redis
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        networks:
            - app-network
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./app:/var/www/html/app
            - ./config:/var/www/html/config
            - ./database:/var/www/html/database
            - ./resources:/var/www/html/resources
            - ./routes:/var/www/html/routes
            - ./tests:/var/www/html/tests
        networks:
            - app-network
